project:
  type: website

website:
  title: "Combustion and Energy Systems Lab"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - research.qmd

      - publications.qmd

      - teaching.qmd

      - blog/index.qmd

      - wiki/index.qmd

format:
  html:
    theme: cosmo
    toc: true