project:
  type: website
  output-dir: docs

website:
  title: "EMC<sup>2</sup> Lab"

  navbar:
    left:
      - href: Home.qmd
        text: Home

      - href: Research.qmd
        text: Research

      - href: Projects.qmd
        text: Projects

      - href: Publications.qmd
        text: Publications

      - href: People.qmd
        text: People

      - href: Teaching.qmd
        text: Teaching

      - href: News.qmd
        text: News

      - href: Openning.qmd
        text: Openning

      - href: Resources.qmd
        text: Resources

format:
  html:
    theme: cosmo
    toc: true
    anchor-sections: false